In [1]:
#import the libraries
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [2]:
# Load the dataset
data=pd.read_csv('E:\Assignment\Assignment 3 - Hypothesis testing\LabTAT.csv')
data.head()

   Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [3]:
data.describe()

       Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [ ]:
'''
Assume Null hyposthesis as Ho: μ1 = μ2 = μ3 = μ4 (There are no significant differences between the groups' mean Lab values)
Thus Alternate hypothesis as Ha: μ1 ≠ μ2 ≠ μ3 ≠ μ4 (There is a significant difference between the groups' mean Lab values)
Here means of more than two population are different, so we are using one-way anova test.
'''

In [4]:
lab1=pd.Series(data.iloc[:,0])
lab1

0      185.35
1      170.49
2      192.77
3      177.33
4      193.41
        ...
115    178.49
116    176.08
117    202.48
118    182.40
119    182.09
Name: Laboratory 1, Length: 120, dtype: float64

In [5]:
lab2=pd.Series(data.iloc[:,1])
lab2

0      165.53
1      185.91
2      194.92
3      183.00
4      169.57
        ...
115    170.66
116    183.98
117    174.54
118    197.18
119    215.17
Name: Laboratory 2, Length: 120, dtype: float64

In [6]:
lab3=pd.Series(data.iloc[:,2])
lab3

0      176.70
1      198.45
2      201.23
3      199.61
4      204.63
        ...
115    193.80
116    215.25
117    203.99
118    194.52
119    221.49
Name: Laboratory 3, Length: 120, dtype: float64

In [7]:
lab4=pd.Series(data.iloc[:,3])
lab4

0      166.13
1      160.79
2      185.18
3      176.42
4      152.60
        ...
115    172.68
116    177.64
117    170.27
118    150.87
119    162.21
Name: Laboratory 4, Length: 120, dtype: float64

In [8]:
# one-way anova
p_value=stats.f_oneway(lab1,lab2,lab3,lab4)
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [ ]:
# compare p_value with α = 0.05 (At 5% significance level)

In [ ]:
'''
 As (p_value=2.1156) > (α = 0.05); Accept Null Hypothesis i.e. μ1 = μ2 = μ3 = μ4 ( Thus, there is no difference in 
 the average Turn Around Time (TAT) of reports of the laboratories on their preferred list.
 '''