# Lab TAT Data

In [1]:
#import the libraries
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [2]:
# Load the dataset
data=pd.read_csv('E:\Assignment\Assignment 3 - Hypothesis testing\LabTAT.csv')
data.head()

   Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [3]:
data.describe()

       Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [ ]:
'''
Assume Null hyposthesis as Ho: μ1 = μ2 = μ3 = μ4 (There are no significant differences between the groups' mean Lab values)
Thus Alternate hypothesis as Ha: μ1 ≠ μ2 ≠ μ3 ≠ μ4 (There is a significant difference between the groups' mean Lab values)
Here means of more than two population are different, so we are using one-way anova test.
'''

In [4]:
lab1=pd.Series(data.iloc[:,0])
lab1

0      185.35
1      170.49
2      192.77
3      177.33
4      193.41
        ...
115    178.49
116    176.08
117    202.48
118    182.40
119    182.09
Name: Laboratory 1, Length: 120, dtype: float64

In [5]:
lab2=pd.Series(data.iloc[:,1])
lab2

0      165.53
1      185.91
2      194.92
3      183.00
4      169.57
        ...
115    170.66
116    183.98
117    174.54
118    197.18
119    215.17
Name: Laboratory 2, Length: 120, dtype: float64

In [6]:
lab3=pd.Series(data.iloc[:,2])
lab3

0      176.70
1      198.45
2      201.23
3      199.61
4      204.63
        ...
115    193.80
116    215.25
117    203.99
118    194.52
119    221.49
Name: Laboratory 3, Length: 120, dtype: float64

In [7]:
lab4=pd.Series(data.iloc[:,3])
lab4

0      166.13
1      160.79
2      185.18
3      176.42
4      152.60
        ...
115    172.68
116    177.64
117    170.27
118    150.87
119    162.21
Name: Laboratory 4, Length: 120, dtype: float64

In [8]:
# one-way anova
p_value=stats.f_oneway(lab1,lab2,lab3,lab4)
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [ ]:
# compare p_value with α = 0.05 (At 5% significance level)

In [ ]:
'''
 As (p_value=2.1156) > (α = 0.05); Accept Null Hypothesis i.e. μ1 = μ2 = μ3 = μ4 ( Thus, there is no difference in 
 the average Turn Around Time (TAT) of reports of the laboratories on their preferred list.
 '''

# Cutlet Dataset

In [1]:
#import the libraries
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

In [2]:
# Load the dataset
data=pd.read_csv('E:\Assignment\Assignment 3 - Hypothesis testing\Cutlets.csv')
data.head()

   Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [3]:
data.describe()

          Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [ ]:
'''
Assume Null hyposthesis as Ho: μ1 = μ2 (There is no difference in diameters of cutlets between two units)
Thus Alternate hypothesis as Ha: μ1 ≠ μ2 (There is significant difference in diameters of cutlets between two units)
2 Sample 2 Tail test applicable
'''

In [4]:
unitA=pd.Series(data.iloc[:,0])
unitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [5]:
unitB=pd.Series(data.iloc[:,1])
unitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [6]:
# 2-sample 2-tail ttest:   stats.ttest_ind(array1,array2)     # ind -> independent samples
p_value=stats.ttest_ind(unitA,unitB)
p_value

Ttest_indResult(statistic=0.7228688704678061, pvalue=0.4722394724599501)

In [7]:
p_value[1]     # 2-tail probability

0.4722394724599501

In [ ]:
# compare p_value with α = 0.05 (At 5% significance level)

In [ ]:
'''
 As (p_value=0.4722) > (α = 0.05); Accept Null Hypothesis i.e. μ1 = μ2 ( Thus, there is no difference in diameters 
 of cutlets between two units
 '''

# Costomer-Order-Form Dataset

In [1]:
#import the libraries
import pandas as pd
import numpy as np
import scipy
from scipy import stats
from scipy.stats import norm

In [2]:
# Load the dataset
data=pd.read_csv('E:\Assignment\Assignment 3 - Hypothesis testing\CostomerOrderForm.csv')
data.head()

  Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [3]:
data.describe()

       Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [4]:
Phillippines_value=data['Phillippines'].value_counts()
Indonesia_value=data['Indonesia'].value_counts()
Malta_value=data['Malta'].value_counts()
India_value=data['India'].value_counts()
print(Phillippines_value)
print(Indonesia_value)
print(Malta_value)
print(India_value)

Error Free    271
Defective      29
Name: Phillippines, dtype: int64
Error Free    267
Defective      33
Name: Indonesia, dtype: int64
Error Free    269
Defective      31
Name: Malta, dtype: int64
Error Free    280
Defective      20
Name: India, dtype: int64

In [5]:
alpha=0.05
errorfree = [271,267,269,280]
defective=[29,33,31,20]
count=[errorfree, defective]
print(count)

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [6]:
chiStats = scipy.stats.chi2_contingency(count)
Chi_pValue=chiStats[1]
print("p-value is: "+str(Chi_pValue))
print('Interpret by p-Value')
if chiStats[1] < 0.05:
  print('we reject null hypothesis')
else:
  print('we accept null hypothesis')

p-value is: 0.2771020991233135
Interpret by p-Value
we accept null hypothesis

# BuyerRatio Dataset

In [1]:
#import the libraries
import pandas as pd
import numpy as np
import scipy
from scipy import stats
from scipy.stats import norm

In [2]:
# Load the dataset
data=pd.read_csv('E:\Assignment\Assignment 3 - Hypothesis testing\BuyerRatio.csv')
data.head()

  Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [3]:
data.describe()

             East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

In [ ]:
'''
Assume Null hyposthesis as Ho: μ1 = μ2 = μ3 = μ4 (There is no significant difference between the groups mean buyerratio 
values)
Thus Alternate hypothesis as Ha: μ1 ≠ μ2 ≠ μ3 ≠ μ4 (There is a significant difference between the groups mean buyerratio
values)
'''

In [4]:
# compare means
East=data['East'].mean()
West=data['West'].mean()
North=data['North'].mean()
South=data['South'].mean()

print('East Mean = ',East)
print('West Mean = ',West)
print('North Mean = ',North)
print('South Mean = ',South)

East Mean =  242.5
West Mean =  832.5
North Mean =  743.5
South Mean =  410.0

In [5]:
alpha=0.05
Male = [50,142,131,70]
Female=[435,1523,1356,750]
Sales=[Male,Female]
print(Sales)

[[50, 142, 131, 70], [435, 1523, 1356, 750]]

In [6]:
# applying chi_square test
Chisquares_results = scipy.stats.chi2_contingency(Sales)
Chi_pValue=Chisquares_results[1]

In [7]:
print("p-value is: "+str(Chi_pValue))
print('Interpret by p-Value')
if Chi_pValue < 0.05:
  print('we reject null hypothesis')
else:
  print('we accept null hypothesis')

p-value is: 0.6603094907091882
Interpret by p-Value
we accept null hypothesis